$(function(){
	if(jsValidate){
		$("#inputForm").validate({
			rules: {
				"enterId":{required: true,maxlength:19,},
				"status":{required: true,maxlength:1,},
				"isPerfect":{required: true,maxlength:1,},
				"companyName":{required: true,maxlength:64,},
				"countryId":{required: true,maxlength:19,},
				"countryName":{required: true,maxlength:64,},
				"provinceId":{required: true,maxlength:19,},
				"provinceName":{required: true,maxlength:64,},
				"cityId":{required: true,maxlength:19,},
				"cityName":{required: true,maxlength:64,},
				"districtId":{required: true,maxlength:19,},
				"districtName":{required: true,maxlength:64,},
				"detailedAddress":{required: true,maxlength:255,},
				"companyPhone":{required: true,maxlength:64,},
				"staffCount":{required: true,maxlength:10,},
				"registeredCapital":{required: true,maxlength:10,},
				"contact":{required: true,maxlength:64,},
				"contactNumber":{required: true,maxlength:64,},
				"qq":{required: true,maxlength:64,},
				"email":{required: true,maxlength:64,},
				"sellerLicense":{required: true,maxlength:64,},
				"sellerLicensePath":{required: true,maxlength:64,},
				"sellerScope":{required: true,maxlength:255,},
				"organizationCode":{required: true,maxlength:64,},
				"organizationCodePath":{required: true,maxlength:64,},
				"generalTaxpayerPath":{required: true,maxlength:64,},
				"accountName":{required: true,maxlength:255,},
				"bankAccount":{required: true,maxlength:64,},
				"bankName":{required: true,maxlength:255,},
				"branchLineContact":{required: true,maxlength:64,},
				"bankCountryId":{required: true,maxlength:19,},
				"bankCountryName":{required: true,maxlength:64,},
				"bankProvinceId":{required: true,maxlength:19,},
				"bankProvinceName":{required: true,maxlength:64,},
				"bankCityId":{required: true,maxlength:19,},
				"bankCityName":{required: true,maxlength:64,},
				"bankDistrictId":{required: true,maxlength:19,},
				"bankDistrictName":{required: true,maxlength:64,},
				"districtImgPath":{required: true,maxlength:64,},
				"settlementAccountName":{required: true,maxlength:64,},
				"settlementBankAccount":{required: true,maxlength:64,},
				"settlementBankName":{required: true,maxlength:64,},
				"settlementBranchLineContact":{required: true,maxlength:64,},
				"settlementCountryId":{required: true,maxlength:19,},
				"settlementCountryName":{required: true,maxlength:64,},
				"settlementProvinceId":{required: true,maxlength:19,},
				"settlementProvinceName":{required: true,maxlength:64,},
				"settlementCityId":{required: true,maxlength:19,},
				"settlementCityName":{required: true,maxlength:64,},
				"settlementDistrictId":{required: true,maxlength:19,},
				"settlementDistrictName":{required: true,maxlength:64,},
				"taxRegistrationNumber":{required: true,maxlength:64,},
				"taxIdentificationNumber":{required: true,maxlength:64,},
				"taxRegistrationNumberPath":{required: true,maxlength:64,},
				"storeName":{required: true,maxlength:64,},
				"levelId":{required: true,maxlength:19,},
				"industryId":{required: true,maxlength:19,},
				"categoryId":{required: true,maxlength:19,},
				"summaryOfCoping":{required: true,maxlength:12,},
				"paymentVoucherPath":{required: true,maxlength:64,},
				"paymentInstructions":{required: true,maxlength:255,},
				"oneAuditOpinion":{required: true,maxlength:255,},
				"twoAuditOpinion":{required: true,maxlength:255,},
				"commission":{required: true,maxlength:12,},
			},
			messages: {
				"enterId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"status":{required: "必填项",maxlength:"最大长度不能超过1字符",},
				"isPerfect":{required: "必填项",maxlength:"最大长度不能超过1字符",},
				"companyName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"countryId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"countryName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"provinceId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"provinceName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"cityId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"cityName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"districtId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"districtName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"detailedAddress":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"companyPhone":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"staffCount":{required: "必填项",maxlength:"最大长度不能超过10字符",},
				"registeredCapital":{required: "必填项",maxlength:"最大长度不能超过10字符",},
				"contact":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"contactNumber":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"qq":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"email":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"sellerLicense":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"sellerLicensePath":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"sellerScope":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"organizationCode":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"organizationCodePath":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"generalTaxpayerPath":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"accountName":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"bankAccount":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"bankName":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"branchLineContact":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"bankCountryId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"bankCountryName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"bankProvinceId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"bankProvinceName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"bankCityId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"bankCityName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"bankDistrictId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"bankDistrictName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"districtImgPath":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementAccountName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementBankAccount":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementBankName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementBranchLineContact":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementCountryId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"settlementCountryName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementProvinceId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"settlementProvinceName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementCityId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"settlementCityName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"settlementDistrictId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"settlementDistrictName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"taxRegistrationNumber":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"taxIdentificationNumber":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"taxRegistrationNumberPath":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"storeName":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"levelId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"industryId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"categoryId":{required: "必填项",maxlength:"最大长度不能超过19字符",},
				"summaryOfCoping":{required: "必填项",maxlength:"最大长度不能超过12字符",},
				"paymentVoucherPath":{required: "必填项",maxlength:"最大长度不能超过64字符",},
				"paymentInstructions":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"oneAuditOpinion":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"twoAuditOpinion":{required: "必填项",maxlength:"最大长度不能超过255字符",},
				"commission":{required: "必填项",maxlength:"最大长度不能超过12字符",},
			},
			errorPlacement: function(error, element) {
				//错误提示信息的显示位置
				if (element.is(":checkbox")||element.is(":radio")||element.parent().is(".input-group")){
					error.appendTo(element.parent().parent());
				} else {
					error.insertAfter(element);
				}
			},
			submitHandler: function(form){
				//对checkbox处理，1：选中；0：未选中
				$("input[type=checkbox]").each(function(){
					$(this).after("<input type=\"hidden\" name=\""+$(this).attr("name")+"\" value=\""
							+($(this).attr("checked")?"1":"0")+"\"/>");
					$(this).attr("name", "_"+$(this).attr("name"));
				});
				layer.msg('正在提交，请稍等...', {icon: 16,shade: 0.30,time: 0});
				form.submit();
			}
		});
	}
});